---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-agent-master
  path: gopath/src/github.com/cloudfoundry/bosh-agent-master
- name: bosh-agent
  path: gopath/src/github.com/cloudfoundry/bosh-agent

run:
  path: gopath/src/github.com/cloudfoundry/bosh-agent-master/ci/bluemix_ng/tasks/test-unit.sh
