---
jobs:
- name: test-unit
  public: true
  plan:
    - get: bosh-agent
      trigger: true
    - task: test-unit
      file: bosh-agent/ci/tasks/test-unit.yml

- name: test-integration
  public: false
  plan:
    - get: bosh-agent
      trigger: true
    - task: test-integration
      privileged: true
      file: bosh-agent/ci/tasks/test-integration.yml
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{BOSH_AWS_ACCESS_KEY_ID}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
        BOSH_LITE_KEYPAIR: {{BOSH_LITE_KEYPAIR}}
        BOSH_LITE_SUBNET_ID: {{BOSH_LITE_SUBNET_ID}}
        BOSH_LITE_NAME: {{BOSH_LITE_NAME}}
        BOSH_LITE_SECURITY_GROUP: {{BOSH_LITE_SECURITY_GROUP}}
        BOSH_LITE_PRIVATE_KEY: {{BOSH_LITE_PRIVATE_KEY}}

- name: windows-test-unit
  serial: true
  plan:
  - get: bosh-agent
    trigger: true
  - task: test-unit
    file: bosh-agent/ci/tasks/test-unit-windows.yml

- name: promote
  public: true
  serial: true
  plan:
    - aggregate:
      - trigger: true
        passed: [test-unit, test-integration, windows-test-unit]
        get: bosh-agent
      - get: version-semver
        params: {bump: patch}
    - put: version-semver
      params:
        file: version-semver/number
    - put: bosh-agent
      params:
        repository: bosh-agent
        tag: version-semver/number
        tag_prefix: v
        only_tag: true
    - aggregate:
      - task: build-linux
        file: bosh-agent/ci/tasks/build-linux.yml
      - task: build-linux-ppc64le
        file: bosh-agent/ci/tasks/build-linux-ppc64le.yml
    - aggregate:
      - put: release-bucket-linux
        params:
          file: compiled-linux-amd64/bosh-agent-*-linux-amd64
      - put: release-bucket-linux-ppc64le
        params:
          file: compiled-linux-ppc64le/bosh-agent-*-linux-ppc64le

resources:
- name: bosh-agent
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-agent.git
    branch: 2.1.x
    private_key: {{BOSH_GITHUB_DEPLOYMENT_KEY}}

- name: release-bucket-linux
  type: s3
  source:
    bucket: releases
    regexp: bosh-agent-(.*)-linux-amd64
    bucket: {{RELEASE_BUCKET_AGENT}}
    region_name: {{AWS_S3_BUCKET_REGION}}
    access_key_id: {{AWS_S3_BUCKET_ACCESS_KEY}}
    secret_access_key: {{AWS_S3_BUCKET_SECRET_KEY}}

- name: release-bucket-linux-ppc64le
  type: s3
  source:
    bucket: releases
    regexp: bosh-agent-(.*)-linux-ppc64le
    bucket: {{RELEASE_BUCKET_AGENT}}
    region_name: {{AWS_S3_BUCKET_REGION}}
    access_key_id: {{AWS_S3_BUCKET_ACCESS_KEY}}
    secret_access_key: {{AWS_S3_BUCKET_SECRET_KEY}}

- name: version-semver
  type: semver
  source:
    initial_version: 2.1.0
    key: agent-2.1-current-version
    bucket: {{SEMVER_BUCKET}}
    region_name: {{AWS_S3_BUCKET_REGION}}
    access_key_id: {{AWS_S3_BUCKET_ACCESS_KEY}}
    secret_access_key: {{AWS_S3_BUCKET_SECRET_KEY}}
